[WIP] Improve infix operator expression parsing
syuilo/aiscript pull request #112
Opened 2021-07-27 16:13 UTC by cwd-k2

#106 での議論に基づいて、中置演算子を含む式のパースを改善した。

`Term` の規則を追加し `Expr` と明確に分けた。
中置演算子を関数呼び出しとしてパースしていた箇所を修正し、インタープリタ時点で対応する関数の呼び出しを行うように変更した。

以上の変更から括弧を使わずに中置演算子式をいい感じに書けるようになった（はず）。

TODO: テストの追加

# What

# Why

# Additional info (optional)

2021-07-28 04:49 UTC, cwd-k2 commented
master 側で `<<` が `return` になってるけど追従しておいた方が良い？

2021-07-28 04:50 UTC, syuilo commented
ｵﾅｼｬｽ🙏

2021-07-28 18:35 UTC, marihachi reviewed
Attrの開始記号"+"とInfixの演算子"+"が干渉してるみたい
Attrは別の記号を使うようにする？

2021-07-28 18:52 UTC, marihachi commented
```
$a <- 1 + if yes 1 else 0
```
この文が正常に処理できないみたい。Infixの項にはExprが含まれないため。

2021-07-28 19:12 UTC, marihachi commented
Infixのような複合的な式の演算で、使える構文に制約があるのがちょっと微妙な気がするな。

2021-07-28 23:25 UTC, cwd-k2 commented
まず根本的に `+` が色々干渉してるのが不味そうな気がしてきた

2021-07-28 23:44 UTC, cwd-k2 commented
`Expr = Infix / Term` となるように修正し、上記の `if` のパースエラーが起きないことを確認した
問題のありそうな箇所があったら教えて欲しい

2021-07-29 03:14 UTC, marihachi commented
boolやattrとしての+は別の語を使うor廃止しないとこのPRはちょっと危険かもね
Attr

2021-07-29 03:25 UTC, marihachi commented
良い感じ！帰ったら見ます

2021-07-29 03:38 UTC, cwd-k2 commented
関連 #118 #97

2021-07-29 12:55 UTC, marihachi commented on src/parser/parser.pegjs
> +	= op:(!ReservedOps [-+*/%&|=~<>!?]+) {	return createNode('operator', { op: text() }); }
このopラベル使ってないし要らなそう？

2021-07-29 13:10 UTC, marihachi commented on src/parser/parser.pegjs
> +	= "<<<" / "<:" / "=>" / "<-" / "+<-" / "-<-"
- ここのopラベル使ってないし要らなそう？
- ReservedOpsの記号から始まる記号列全てが演算子として使えなくなるかも。次の文字が演算子の記号じゃないことを先読みしたほうが良さそう(そんなに長い演算子があるか分からないけど)

記号を可変にしてるのは何か意図があるのかな？任意の記号とマッチするのは干渉のリスクが結構高い気がする。

2021-07-29 13:56 UTC, cwd-k2 commented on src/parser/parser.pegjs
> +	= "<<<" / "<:" / "=>" / "<-" / "+<-" / "-<-"
> 記号を可変にしてる意図
干渉する以外に制限する理由が特に思いつかなかったので出来るようにしてある感じ
干渉をうまいこと回避する方法を探す必要がありそう
個人的に演算子と識別子を同レベルで考えてるのかもしれない

> 演算子の記号じゃないことを先読み
確かにそうかも

2021-07-29 14:07 UTC, cwd-k2 commented
Attr との干渉、「演算子の前での改行を認めない」とかのルールを追加したら少し改善されたりする可能性ある？

2021-07-30 10:47 UTC, marihachi commented
> Attr との干渉、「演算子の前での改行を認めない」とかのルールを追加したら少し改善されたりする可能性ある？ 

あるかも？

2021-07-30 10:56 UTC, marihachi requested changes
> Attr との干渉、「演算子の前での改行を認めない」とかのルールを追加したら少し改善されたりする可能性ある？ 

言語としての検討の余地がありそうなので、一旦このPRでは範囲外としたい。
Revertお願いします。

2021-07-30 12:13 UTC, marihachi approved these changes

2021-07-30 12:21 UTC, syuilo commented on src/interpreter/index.ts
> +			}
ここで`Core:add`とか返すくらいなら直接計算しちゃった方がパフォーマンス良さそうだけどどうだろう？
仮にそうするとしたらこのPRでなくてもいいけど

2021-07-30 12:47 UTC, cwd-k2 commented on src/interpreter/index.ts
> +			}
eval して関数の定義を拾ってくるわけではなくインタプリタ上で数値などとして計算するってこと？
実際にどれくらいパフォーマンスに影響するかな

この辺は AiScript 側に演算子の定義があってそれを拾ってくる形が嬉しいみたいな気持ちもある（それなら今後演算子を追加することがあったときにインタプリタを触るのではなくstdに定義すればよいだけになる）

2021-07-30 12:49 UTC, syuilo commented on src/interpreter/index.ts
> +			}
> eval して関数の定義を拾ってくるわけではなくインタプリタ上で数値などとして計算するってこと？

よく考えたらちょっと面倒そうだ
マージします🙏

2021-07-30 12:49 UTC, merged

2021-07-30 12:50 UTC, syuilo commented
🙏🏿