For, ForOf takes Statements instead of Expr
syuilo/aiscript pull request #95
Opened 2021-07-24 05:57 UTC by cwd-k2

`For`, `ForOf` が `Expr` を期待していたが、見た感じ基本的に `Block` を期待しているようだったので `Statements` に置き換えました

2021-07-24 06:05 UTC, marihachi commented
1つの式を受け入れられなくなってない？

2021-07-24 06:12 UTC, cwd-k2 commented
ひとつの式
```
for (#i, 15) Arr:push(arr, i)
```
みたいなものか

`Loop` だと初めから `{ _ Statements _ }` 前提だけど `_ Statement _ / { _ Statements  _ }` みたいにした方がいいってことかな

2021-07-24 07:10 UTC, marihachi commented
Statementだけで良いかも。StatementにはBlockも含まれるし

2021-07-24 07:13 UTC, syuilo commented
loopがforと違い式を受け入れられないようにしたのは、break出来ないから無限ループに陥ることが確実なため

2021-07-24 07:26 UTC, syuilo commented
このPRの目的は何かな？リファクタ？

2021-07-24 07:29 UTC, cwd-k2 commented
#92 を進める前提で Statement と Expr 周りを整理してる

2021-07-24 07:37 UTC, cwd-k2 commented
あとExprを受け取る感じだと代入やインクリメント、`<:`がブロック無しで書けないのかなとも思う

2021-07-24 09:35 UTC, marihachi requested changes
必須スペースの方が良さそうな箇所があった。
Statementにすれば、複数行の場合にもBlockを使えるので大丈夫という認識。

2021-07-24 09:35 UTC, marihachi commented on src/parser/parser.pegjs
> +	/ "~" ___ "#" varn:NAME _ from:("=" _ v:Expr { return v; })? ","? _ to:Expr _ x:Statement
ここのexprとstatementの間は必須スペースじゃないと不自然そう

2021-07-24 09:35 UTC, marihachi commented on src/parser/parser.pegjs
> +	/ "~" ___ times:Expr _ x:Statement
ここも必須スペース

2021-07-24 09:35 UTC, marihachi commented on src/parser/parser.pegjs
> +	/ "for" ___ "#" varn:NAME _ from:("=" _ v:Expr { return v; })? ","? _ to:Expr _ x:Statement
ここも必須スペース

2021-07-24 09:35 UTC, marihachi commented on src/parser/parser.pegjs
> +	/ "for" ___ times:Expr _ x:Statement
ここも必須スペース

2021-07-24 09:35 UTC, marihachi commented on src/parser/parser.pegjs
> +	/ "~~" ___ "#" varn:NAME _ ","? _ items:Expr _ x:Statement
ここも必須スペース

2021-07-24 09:35 UTC, marihachi commented on src/parser/parser.pegjs
> +	/ "each" ___ "#" varn:NAME _ ","? _ items:Expr _ x:Statement
ここも必須スペース

2021-07-25 04:54 UTC, syuilo commented on test/index.ts
> +	});
💯

2021-07-25 04:55 UTC, syuilo commented on test/index.ts
> +	})
💯

2021-07-25 04:56 UTC, syuilo approved these changes
yosasou

2021-07-25 10:45 UTC, marihachi approved these changes
YOSASOU

2021-07-25 10:45 UTC, merged